### ISSUE TITLE
Formatted fields?

### ISSUE THREAD

**Issue by Speekless** [binaryplayground/acf-field-star-rating#1]
Hi, I've stumbled across your plugin (great initiative!) and I'm trying to use it, but `the_field()` only returns a numerical value. Is this correct and expected behaviour? Do you have a way to display the formatted 5 stars on the front-end?

Thanks,
Pim

**Comment by findingsimple** [comment]
Hi - that is intended. So that it can be displayed however desired on the front end.
E.g. you could use http://wbotelhos.com/raty, built it into the theme, create a custom widget etc.

**Comment by Speekless** [comment]
Great, thank you very much for the suggestion.

**Comment by Speekless** [comment]
Another question: is there any functionality at all to update the field and keep track of the number of ratings, as to display an average? Otherwise, isn't this just an integer field? :)

**Comment by findingsimple** [comment]
That is correct - like a lot of ACF fields this just provides a nicer more familiar interface for storing custom post meta.

There is the ability to add an average field which tallys up multiple review values(? I guess you'd call them)

Update - http://cl.ly/image/1v2k1v013400

Update 2 -  I should also point out/clarify - this is for admin/authors to provide ratings. The use case isn't really intended for general visitors coming to your site.
