### ISSUE TITLE
Echoing the Image Rating

### ISSUE THREAD

**Issue by criana** [binaryplayground/acf-field-star-rating#2]
I've implemented the plugin on my site, but am only getting a text representation of the rating when calling for the field. I added the action to register the fields in my functions file as well.

I'm using the following code in between Div tags, <?php the_field('testi-rating'); ?>

**Comment by findingsimple** [comment]
> only getting a text representation of the rating

That is intended. It doesn't do anything on the front end. Its for creating a rating field in the WP dashboard. You can create a custom widget, customise your theme etc to display ratings however you choose using something like http://wbotelhos.com/raty / https://github.com/wbotelhos/raty

Ref. previous issue https://github.com/FindingSimple/acf-field-star-rating/issues/1
