### ISSUE TITLE
Stars not displaying

### ISSUE THREAD

**Issue by clementdes** [binaryplayground/acf-field-star-rating#5]
Hello 
ACF version 4.3.9
Wordpress version 3.9
Installed ACF rating system as a plugin.

Hi I am trying to display the stars automatically by using : 

<?php $field3 = get_field('general_rating', $doctor->ID );?>
<?php echo $field3 ; ?>

 but it wasn't working probably : only displaying the value in number 3.75, but no star. Could you help ?

FYI : I tried to get the value, key, number by myself, it works. But even by using the HTML code of the plugin the#star div isn't displaying cause of my path to the images.

Thx a lot !

**Comment by findingsimple** [comment]
Hi clementdes

It's not intended to display stars on the front end. It's for creating a rating field in the WP dashboard. You can create a custom widget, customise your theme etc to display ratings however you choose using something like http://wbotelhos.com/raty / https://github.com/wbotelhos/raty

Ref: https://github.com/FindingSimple/acf-field-star-rating/issues/2#issuecomment-46744096

**Comment by clementdes** [comment]
OK, thx  ;)

**Comment by findingsimple** [comment]
Here's another link to raty -> https://github.com/wbotelhos/raty Seems like the main site is down at the moment
